"""add notification_logs.emailed_at

Revision ID: 822df0e14869
Revises: dfe33474e50a
Create Date: 2026-09-04 06:28:55.959415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '822df0e14869'
down_revision: Union[str, Sequence[str], None] = 'dfe33474e50a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_logs', sa.Column('emailed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_logs', 'emailed_at')
    # ### end Alembic commands ###
