"""initial schema

Revision ID: d68f3f123a01
Revises: 
Create Date: 2026-08-25 11:16:03.954320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd68f3f123a01'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('announcement_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('agency', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('announce_date', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('original_url', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('announcement_id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_announcements_source_external')
    )
    op.create_index('idx_announcements_end_date', 'announcements', ['end_date'], unique=False)
    op.create_index('idx_announcements_status_agency_dept', 'announcements', ['status', 'agency', 'department'], unique=False)
    op.create_table('employees',
    sa.Column('employee_no', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('employee_no')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('employee_no', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_no'], ['employees.employee_no'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('employee_no')
    )
    op.create_table('keywords',
    sa.Column('keyword_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(keyword) BETWEEN 1 AND 50', name='chk_keywords_length'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('keyword_id'),
    sa.UniqueConstraint('user_id', 'keyword', name='uq_keywords_user_keyword')
    )
    op.create_table('saved_announcements',
    sa.Column('saved_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('announcement_id', sa.UUID(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.announcement_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('saved_id'),
    sa.UniqueConstraint('user_id', 'announcement_id', name='uq_saved_user_announcement')
    )
    op.create_table('alert_settings',
    sa.Column('setting_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('keyword_id', sa.UUID(), nullable=False),
    sa.Column('dashboard_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('email_frequency', sa.String(), nullable=True),
    sa.Column('email_send_time', sa.Time(), nullable=True),
    sa.Column('alert_d7', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('alert_d3', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('alert_d1', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.keyword_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('setting_id'),
    sa.UniqueConstraint('keyword_id')
    )
    op.create_table('notification_logs',
    sa.Column('log_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('announcement_id', sa.UUID(), nullable=True),
    sa.Column('keyword_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('notify_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'success'"), nullable=False),
    sa.Column('sent_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.announcement_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.keyword_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id'),
    sa.UniqueConstraint('user_id', 'announcement_id', 'notify_type', name='uq_notification_dedup')
    )
    op.create_index('idx_notification_logs_user_sent', 'notification_logs', ['user_id', 'sent_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_notification_logs_user_sent', table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_table('alert_settings')
    op.drop_table('saved_announcements')
    op.drop_table('keywords')
    op.drop_table('users')
    op.drop_table('employees')
    op.drop_index('idx_announcements_status_agency_dept', table_name='announcements')
    op.drop_index('idx_announcements_end_date', table_name='announcements')
    op.drop_table('announcements')
    # ### end Alembic commands ###
